### PR TITLE
Catch-all routes

### PR DESCRIPTION
**Pull request by spencewood**
This simply pulls in the latest code from https://github.com/danielcondemarin/serverless-next.js/blob/master/packages/serverless-nextjs-component/lib/expressifyDynamicRoute.js which supports dynamic catch all routes.

### CODE REVIEW

**Comment by alxhghs** [comment]
I forked this branch to use for my current site which has catchall routes and I can attest to it seeming to work well. Seems like this would be good to add! Once it's merged in I'll be able to remove my fork :) thanks for this

**Comment by Yagogc** [comment]
Please mind a silly question:

I'm having issues with `next-on-netlify` by getting query params from `getServerSideProps`. Does this PR fix that issue? (Note: the same app works in now.sh, so I guess the issue relates to Netlify and this plugin)

Thanks!

**Comment by spencewood** [comment]
I believe the issue with netlify and `getServerSideProps` is due to the fact that Next returns the server side props with this new method in a separate .json request instead of including it in the body like `getInitialProps`. Some additional rewriting or routing would need to be included to support this, but this particular change does not address it.

**Comment by Djepri** [comment]
Hi I'm a newbie on this js world
How I can make these routes to work:
http://localhost:8888/g/lmB0i6Ybt~4
http://localhost:8888/search?keyword=foo bar

Thanks

**Comment by FinnWoelm** [comment]
Hi @spencewood and @alxhghs,

this is great! :raised_hands: Thank for you opening this pull request.

Sorry for taking so long to get back. Somehow this totally slipped my attention. I'm on it now and will hopefully merge the changes today. :rocket: 

I'll keep you posted.

PS: @Yagogc, thanks for pointing out the issue with `getServerSideProps`. I'll look into that.

**Comment by FinnWoelm** [comment]
Oh no, I was adding some commits to this PR and messed up a forced push. :grimacing: 

It automatically closed this PR and I can't reopen this one. I've repushed the commits to a new PR (#5). Sincere apologies about that... :sob:

**Comment by FinnWoelm** [comment]
Happy to say that the latest release of `next-on-netlify` (v1.1.0) brings full support for catch-all routing! Check it out: https://next-on.netlify.app/shows/73/whatever/path/you/want

Thank you @spencewood and @alxhghs for your excellent contributions (and sorry again for messing up this PR... :see_no_evil:)

**Comment by FinnWoelm** [comment]
Hey @Yagogc,

I know it's been a while, but I'm happy to report that `next-on-netlify` **finally supports both `getServerSideProps` and `getStaticProps`** :grin: :tada: 

Here's the full list of changes for `next-on-netlify` v2.0.0: https://github.com/FinnWoelm/next-on-netlify/blob/master/CHANGELOG.md#200-2020-06-02

Let me know if you have any questions or run into any issues!

Happy hacking :fire: 
Finn

**Pull request closed without merging**
